"""add fields for user

Revision ID: 3a63e3eb26bd
Revises: e4eb3d086c83
Create Date: 2018-08-03 17:07:08.004568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a63e3eb26bd'
down_revision = 'e4eb3d086c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
